### ISSUE TITLE
Packaging & publishing on PyPI

### ISSUE THREAD

**Issue by ninoseki** [CybercentreCanada/pysigma#16]
Hello, thank you for creating a good library.
It will be great if I can install this library by `pip install ...`. Do you have a plain for that?

**Comment by cccs-rs** [comment]
Hello!

Technically you can do a pip install via: `pip install git+https://github.com/CybercentreCanada/pysigma.git`

There hasn't been any plans to publish the package to repository like PyPI.

**Comment by ninoseki** [comment]
Thanks I got it.
